### ISSUE TITLE
About Setuptools

### ISSUE THREAD

**Issue by wkranti** [kylerbrown/textgrid#2]
In file named setup.py
from setuptools import setup
what does this line corresonds?
there is no file or module named setuptools.
Similarly in textgrid.py module named collections

**Comment by kylerbrown** [comment]
Hello @wkranti 

Setuptools is a module for installing python packages, you can install setuptools with pip. For example:

`pip install setuptools`

The `collections` module is built into the standard library. [Here's the documentation](https://docs.python.org/3/library/collections.html)

This might be a useful resource for you: https://python.swaroopch.com/modules.html

Good luck!
